# Generated by Django 5.0.3 on 2024-04-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.FileField(blank=True, default='images/profile/default.jpg', null=True, upload_to='images/profile'),
        ),
    ]
