# Generated by Django 5.0.3 on 2024-04-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_reservedslots'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedslots',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
