# Generated by Django 5.0.3 on 2024-04-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_reservedslots_ticket_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservedslots',
            name='vehicle_type',
        ),
    ]
