# Generated by Django 5.0.3 on 2024-04-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_reservedzones'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedzones',
            name='checkout',
            field=models.BooleanField(default=False),
        ),
    ]
