# Generated by Django 5.0.3 on 2024-04-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_reservedzones_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservedzones',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='reservedzones',
            name='user',
        ),
        migrations.AlterField(
            model_name='reservedzones',
            name='is_reserved',
            field=models.BooleanField(default=True),
        ),
    ]
