# Generated by Django 5.0.3 on 2024-04-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_reservedzones_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedslots',
            name='checkin',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
