# Generated by Django 5.0.3 on 2024-04-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_reservedslots_checkin_delete_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedslots',
            name='checkin',
            field=models.BooleanField(default=False),
        ),
    ]
