# Generated by Django 5.0.3 on 2024-04-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_zone_reservedzones_zones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservedzones',
            old_name='zones',
            new_name='zone',
        ),
    ]
