# Generated by Django 5.0.3 on 2024-04-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='cardNumber',
            new_name='cardnumber',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='cv',
            new_name='cvv',
        ),
        migrations.AlterField(
            model_name='payment',
            name='expirationDate',
            field=models.CharField(max_length=10),
        ),
    ]
