# Generated by Django 5.0.3 on 2024-04-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedslots',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
