# Generated by Django 5.0.3 on 2024-04-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_reservedslots_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedzones',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
