# Generated by Django 5.0.3 on 2024-06-27 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_reservedzones_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=200)),
                ('dob', models.DateField(null=True)),
                ('skills', models.TextField()),
                ('experience', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending')], default='pending', max_length=200)),
                ('specialized_in', models.CharField(choices=[('two_wheeler', 'Two Wheeler'), ('four_wheeler', 'Four Wheeler'), ('heavy_vehicle', 'Heavy Vehicle')], max_length=200)),
                ('bio', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(blank=True, default='static/images/profile/default.jpg', null=True, upload_to='mech_pics')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_location', to='api.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReqToMechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('Payment Pending', 'Payment Pending'), ('pending', 'Pending')], default='pending', max_length=200)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_location', to='api.location')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_profile', to='api.mechanicprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending')], default='pending', max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mechanicprofile')),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reqtomechanic')),
            ],
        ),
    ]
