# Generated by Django 5.0.3 on 2024-06-27 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_mechanicprofile_reqtomechanic_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanicprofile',
            name='skills',
        ),
    ]
