# Generated by Django 5.0.3 on 2024-06-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_mechanicprofile_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reqtomechanic',
            old_name='discription',
            new_name='description',
        ),
    ]
