# Generated by Django 5.0.3 on 2024-06-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_rename_discription_reqtomechanic_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='status',
        ),
    ]
