# Generated by Django 5.0.3 on 2024-06-27 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_bill_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackMechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_mechanicprofile', to='api.mechanicprofile')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_req', to='api.reqtomechanic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acholdername', models.CharField(max_length=100)),
                ('accno', models.PositiveBigIntegerField()),
                ('cvv', models.IntegerField()),
                ('exp', models.DateField()),
                ('amount', models.PositiveBigIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust_pay', to=settings.AUTH_USER_MODEL)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mech_pay', to='api.mechanicprofile')),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pay', to='api.reqtomechanic')),
            ],
        ),
    ]
