# Generated by Django 5.0.3 on 2024-06-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_userpayment_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='users',
            field=models.CharField(choices=[('User', 'User'), ('Mecchanic', 'Mechanic')], max_length=100, null=True),
        ),
    ]
